version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-biblioteca
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: 'biblioteca'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'root'
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
